/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceCreateNamespaceRequest struct for NamespaceServiceCreateNamespaceRequest
type NamespaceServiceCreateNamespaceRequest struct {
	// User provided namespace (verified unique)  <p>can not include dots or slashes (.|/) in the name</p>
	Namespace string `json:"namespace"`
	// Default project id for this tenant when creating buckets
	DefaultObjectProject *string `json:"default_object_project,omitempty"`
	// Default replication group identifier for this tenant when creating buckets
	DefaultDataServicesVpool *string `json:"default_data_services_vpool,omitempty"`
	// List of replication groups that are allowed to create buckets on the corresponding namespace
	AllowedVpoolsList []string `json:"allowed_vpools_list,omitempty"`
	// List of replication groups that are not allowed to create buckets on the corresponding namespace
	DisallowedVpoolsList []string `json:"disallowed_vpools_list,omitempty"`
	// Comma separated list of namespace admins
	NamespaceAdmins *string `json:"namespace_admins,omitempty"`
	// List of user mappings
	UserMapping []NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner `json:"user_mapping,omitempty"`
	// tag to enable encryption for the namespace
	IsEncryptionEnabled *bool `json:"is_encryption_enabled,omitempty"`
	// Default bucket quota size.
	DefaultBucketBlockSize *int64 `json:"default_bucket_block_size,omitempty"`
	// List of groups from AD Server
	ExternalGroupAdmins *string `json:"external_group_admins,omitempty"`
	// Tag to allow stale data within the namespace
	IsStaleAllowed *bool `json:"is_stale_allowed,omitempty"`
	// Optional  <br>  Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Existing buckets are not affected by this flag.  <br>  When true the is_object_lock_with_ado_allowed flag is applied to new buckets allowing them to enable  Object Lock with ADO without having to explicitly enable the flag on the bucket.  <br>  When false or omitted, buckets created in the namespace will not be allowed to enable OBJECT LOCK with writable ADO unless  the is_object_lock_with_ado_allowed flag is explicitly enabled on the bucket.  <br>  The flag only affects new buckets.  Existing buckets must set the flag explicitly to allow Object Lock with ADO.  <br>  Warning: Once the flag is enabled on a bucket it cannot be changed. Make sure you understand the risk of data loss before enabling this flag. See the Admin Guide for more information.
	IsObjectLockWithAdoAllowed *bool `json:"is_object_lock_with_ado_allowed,omitempty"`
	// Tag to enable namespace compliance
	ComplianceEnabled *bool `json:"compliance_enabled,omitempty"`
	// default bucket audit delete expiration
	DefaultAuditDeleteExpiration *int64 `json:"default_audit_delete_expiration,omitempty"`
	// password for namespace 'virtual root' user
	RootUserPassword *string `json:"root_user_password,omitempty"`
}
