/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceGetRetentionClassResponse struct for NamespaceServiceGetRetentionClassResponse
type NamespaceServiceGetRetentionClassResponse struct {
	// Name of the retention class
	Name *string `json:"name,omitempty"`
	// Period of the retention class in seconds
	Period *int64 `json:"period,omitempty"`
}
