/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceGetNamespacesResponseNamespaceInnerVdcLink Hyperlink to the related object
type NamespaceServiceGetNamespacesResponseNamespaceInnerVdcLink struct {
	// Relationship type of the hyperlink
	Rel *string `json:"rel,omitempty"`
	// Hyperlink URL to the related resource
	Href *string `json:"href,omitempty"`
}
