/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceUpdateNamespaceQuotaRequest struct for NamespaceServiceUpdateNamespaceQuotaRequest
type NamespaceServiceUpdateNamespaceQuotaRequest struct {
	// Block size in GB.
	BlockSize *int64 `json:"blockSize,omitempty"`
	// Notification size in GB.
	NotificationSize *int64 `json:"notificationSize,omitempty"`
	// Block size in Count.
	BlockSizeInCount *int64 `json:"blockSizeInCount,omitempty"`
	// Notification size in Count.
	NotificationSizeInCount *int64 `json:"notificationSizeInCount,omitempty"`
}
