/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceGetNamespacesResponseNamespaceInnerLink struct for NamespaceServiceGetNamespacesResponseNamespaceInnerLink
type NamespaceServiceGetNamespacesResponseNamespaceInnerLink struct {
	// Relationship of the Hyperlink
	Rel *string `json:"rel,omitempty"`
	// Hyperlink to the details for this resource
	Href *string `json:"href,omitempty"`
}
