/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceGetNamespacesResponse struct for NamespaceServiceGetNamespacesResponse
type NamespaceServiceGetNamespacesResponse struct {
	// A list of namespaces
	Namespace []NamespaceServiceGetNamespacesResponseNamespaceInner `json:"namespace,omitempty"`
	// Number of Namespaces requested.
	MaxNamespaces *int32 `json:"MaxNamespaces,omitempty"`
	// Reference object to retrieve next set of objects.
	NextMarker *string `json:"NextMarker,omitempty"`
	// filter used to get the objects.
	Filter *string `json:"Filter,omitempty"`
	// link to get the next page.
	NextPageLink *string `json:"NextPageLink,omitempty"`
}
