/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner struct for NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner
type NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner struct {
	// A single-valued attribute indicating the user's IDP domain
	Domain    string                                                                              `json:"domain"`
	Attribute []NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributeInner `json:"attribute,omitempty"`
	Group     []string                                                                            `json:"group,omitempty"`
}
