/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceGetNamespacesResponseNamespaceInnerVdc struct for NamespaceServiceGetNamespacesResponseNamespaceInnerVdc
type NamespaceServiceGetNamespacesResponseNamespaceInnerVdc struct {
	// ECS Id of the related object
	Id   *string                                                     `json:"id,omitempty"`
	Link *NamespaceServiceGetNamespacesResponseNamespaceInnerVdcLink `json:"link,omitempty"`
}
