/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceUpdateNamespaceRequest struct for NamespaceServiceUpdateNamespaceRequest
type NamespaceServiceUpdateNamespaceRequest struct {
	// Default replication group identifier when creating buckets
	DefaultDataServicesVpool *string `json:"default_data_services_vpool,omitempty"`
	// List of replication group identifier which will be added in the allowed List for allowing namespace access
	VpoolsAddedToAllowedVpoolsList []string `json:"vpools_added_to_allowed_vpools_list,omitempty"`
	// List of replication group identifier which will be added in the disAllowed list for prohibiting namespace access
	VpoolsAddedToDisallowedVpoolsList []string `json:"vpools_added_to_disallowed_vpools_list,omitempty"`
	// List of replication group identifier which will be removed from allowed list
	VpoolsRemovedFromAllowedVpoolsList []string `json:"vpools_removed_from_allowed_vpools_list,omitempty"`
	// List of replication group identifier which will be removed from disAllowed list for removing their prohibition namespace access
	VpoolsRemovedFromDisallowedVpoolsList []string `json:"vpools_removed_from_disallowed_vpools_list,omitempty"`
	// Comma separated list of namespace admins
	NamespaceAdmins *string `json:"namespace_admins,omitempty"`
	// List of user mappings for this tenant
	UserMapping []NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner `json:"user_mapping"`
	// Default bucket quota size.
	DefaultBucketBlockSize *int64 `json:"default_bucket_block_size,omitempty"`
	// List of groups from AD Server
	ExternalGroupAdmins *string `json:"external_group_admins,omitempty"`
	// Does request contain update of encryption enabled of namespace.  If null then encryption update is not requested else it is.
	IsEncryptionEnabled *bool `json:"is_encryption_enabled,omitempty"`
	// isStaleAllowed flag of the namespace.
	IsStaleAllowed *bool `json:"is_stale_allowed,omitempty"`
	// Optional  <br>  Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Existing buckets are not affected by this flag.  <br>  When true the is_object_lock_with_ado_allowed flag is applied to new buckets allowing them to enable  Object Lock with ADO without having to explicitly enable the flag on the bucket.  <br>  When false or omitted, buckets created in the namespace will not be allowed to enable OBJECT LOCK with writable ADO unless  the is_object_lock_with_ado_allowed flag is explicitly enabled on the bucket.  <br>  The flag only affects new buckets.  Existing buckets must set the flag explicitly to allow Object Lock with ADO.  <br>  Warning: Once the flag is enabled on a bucket it cannot be changed. Make sure you understand the risk of data loss before enabling this flag. See the Admin Guide for more information.
	IsObjectLockWithAdoAllowed *bool `json:"is_object_lock_with_ado_allowed,omitempty"`
	// default bucket audit delete expiration
	DefaultAuditDeleteExpiration *int64 `json:"default_audit_delete_expiration,omitempty"`
	// Current password for namespace 'virtual root' user
	CurrentRootUserPassword *string `json:"current_root_user_password,omitempty"`
	// New password for namespace 'virtual root' user
	NewRootUserPassword *string `json:"new_root_user_password,omitempty"`
}
