/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributeInner struct for NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributeInner
type NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributeInner struct {
	// Lookup string for this key-value pair
	Key string `json:"key"`
	// Lookup result for this key-value pair
	Value []string `json:"value"`
}
