/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceGetNamespaceQuotaResponse struct for NamespaceServiceGetNamespaceQuotaResponse
type NamespaceServiceGetNamespaceQuotaResponse struct {
	// Gets Namespace
	Namespace *string `json:"namespace,omitempty"`
	// Block size in GB.
	BlockSize *int64 `json:"blockSize,omitempty"`
	// Notification size in GB.
	NotificationSize *int64 `json:"notificationSize,omitempty"`
	// Block size in count.
	BlockSizeInCount *int64 `json:"blockSizeInCount,omitempty"`
	// Notification size in count.
	NotificationSizeInCount *int64 `json:"notificationSizeInCount,omitempty"`
}
