/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NamespaceServiceCreateNamespaceResponse struct for NamespaceServiceCreateNamespaceResponse
type NamespaceServiceCreateNamespaceResponse struct {
	// Default replication group identifier for this tenant when creating buckets
	DefaultDataServicesVpool *string `json:"default_data_services_vpool,omitempty"`
	// List of replication group that are allowed access to namespace
	AllowedVpoolsList []string `json:"allowed_vpools_list,omitempty"`
	// List of replication group that are not allowed access to namespace
	DisallowedVpoolsList []string `json:"disallowed_vpools_list"`
	// Comma separated list of namespace admins
	NamespaceAdmins *string `json:"namespace_admins,omitempty"`
	// encryption status of the namesapce
	IsEncryptionEnabled *string `json:"is_encryption_enabled,omitempty"`
	// List of user mappings for this tenant
	UserMapping []NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner `json:"user_mapping,omitempty"`
	// Default bucket quota size.
	DefaultBucketBlockSize *int64 `json:"default_bucket_block_size,omitempty"`
	// List of groups from AD Server
	ExternalGroupAdmins *string `json:"external_group_admins,omitempty"`
	// Namespace isStaleAllowed flag
	IsStaleAllowed *bool `json:"is_stale_allowed,omitempty"`
	// Optional  <br>  Defines the default behavior for allowing Object Lock with ADO on new buckets created in the namespace. Existing buckets are not affected by this flag.  <br>  When true the is_object_lock_with_ado_allowed flag is applied to new buckets allowing them to enable  Object Lock with ADO without having to explicitly enable the flag on the bucket.  <br>  When false or omitted, buckets created in the namespace will not be allowed to enable OBJECT LOCK with writable ADO unless  the is_object_lock_with_ado_allowed flag is explicitly enabled on the bucket.  <br>  The flag only affects new buckets.  Existing buckets must set the flag explicitly to allow Object Lock with ADO.  <br>  Warning: Once the flag is enabled on a bucket it cannot be changed. Make sure you understand the risk of data loss before enabling this flag. See the Admin Guide for more information.
	IsObjectLockWithAdoAllowed *bool `json:"is_object_lock_with_ado_allowed,omitempty"`
	// Namespace isComplianceEnabled flag
	IsComplianceEnabled *bool `json:"is_compliance_enabled,omitempty"`
	// Notification Size in GB.
	NotificationSize *int64 `json:"notificationSize,omitempty"`
	// Blocksize in GB
	BlockSize *int64 `json:"blockSize,omitempty"`
	// Notification Size in Count.
	NotificationSizeInCount *int64 `json:"notificationSizeInCount,omitempty"`
	// Blocksize in Count
	BlockSizeInCount *int64                                                               `json:"blockSizeInCount,omitempty"`
	RetentionClasses *NamespaceServiceGetNamespacesResponseNamespaceInnerRetentionClasses `json:"retention_classes,omitempty"`
	// Default bucket audit delete expiration
	DefaultAuditDeleteExpiration *int64  `json:"default_audit_delete_expiration,omitempty"`
	RootUserName                 *string `json:"root_user_name,omitempty"`
	RootUserPassword             *string `json:"root_user_password,omitempty"`
	// Name assigned to this resource in ECS. The resource name is set by  a user and can be changed at any time. It is not a unique identifier.
	Name *string `json:"name,omitempty"`
	// Identifier that is generated by ECS when the resource is created.  The resource Id is guaranteed to be unique  and  immutable across all  virtual data centers for all time.
	Id   *string                                                  `json:"id,omitempty"`
	Link *NamespaceServiceGetNamespacesResponseNamespaceInnerLink `json:"link,omitempty"`
	// Timestamp that shows when this resource was created in ECS
	CreationTime *int64 `json:"creation_time,omitempty"`
	// Indicates whether the resource is inactive. When a user removes  a resource, the resource is put in this state before  it is removed from the ECS database.
	Inactive *bool `json:"inactive,omitempty"`
	// Indicates whether the resource is global.
	Global *bool `json:"global,omitempty"`
	// Indicates whether the resource is remote.
	Remote *bool                                                   `json:"remote,omitempty"`
	Vdc    *NamespaceServiceGetNamespacesResponseNamespaceInnerVdc `json:"vdc,omitempty"`
	// Indicated whether the resource is an internal resource
	Internal *bool `json:"internal,omitempty"`
}
